name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Luacheck
        uses: nebularg/actions-luacheck@86af42dcf465915896671903fcdec3e01a492e87
        with:
          args: --no-color -o 011
